### ISSUE TITLE
As an user I want to build and publish the Atom Plugin to atom tool for Fabric composer developers. 

### ISSUE THREAD

**Issue by xufengli** [fabric-composer/tools#2]
This story covers build and publish tasks for the Atom plugin source code so that Fabric composer developers can install it from Atom catalog.

**Comment by dselman** [comment]
Please move this under the main fabric-composer Issues project, we are trying to keep all the issues together for easier review/maintenance.

**Comment by xufengli** [comment]
move it and close this one now
